
all:	rtlsdr.dll

rtlsdr.dll:	rtlsdr-bridge.c signal-queue.c gains.h gains.c rtlsdr-bridge-resource.o
	i686-w64-mingw32-gcc -O2 -fPIC -g -shared -D__DEBUG__ -I . -I /usr/i686-w64-mingw32/sysroot/mingw/include  -o rtlsdr.dll rtlsdr-bridge.c signal-queue.c gains.c  rtlsdr-bridge-resource.o mir_sdr_api.dll.a libwinpthread-1.dll -lgdi32

rtlsdr-bridge-resource.o	: rtlsdr-bridge.rc
	i686-w64-mingw32-windres rtlsdr-bridge.rc rtlsdr-bridge-resource.o

clean:
	rm *.o rtlsdr.dll
